name: Image API checks
on:
  push:
    paths:
      - image-api/**
jobs:
  test-image-api:
    name: Image API Unit Tests
    defaults:
      run:
        working-directory: image-api

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      - run: yarn install --frozen-lockfile

      - run: yarn test

  lint-image-api:
    name: Image API Linting
    defaults:
      run:
        working-directory: image-api

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      - run: yarn install --frozen-lockfile

      - run: yarn lint
