name: Image API checks
on:
  push:
    paths:
      - 'image-api/**'
      - '.github/workflows/image-api.yml'
jobs:
  test:
    name: Unit Tests
    defaults:
      run:
        working-directory: image-api

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      - run: yarn install --frozen-lockfile

      - run: yarn test

  lint:
    name: Linting
    defaults:
      run:
        working-directory: image-api

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0

      - run: yarn install --frozen-lockfile

      - run: yarn lint
